spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codechallenge_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-main.yaml

migration:
  dual-write:
    enabled: false
    read-source: LEGACY_ONLY # Options: NEW_WITH_FALLBACK, NEW_ONLY, LEGACY_ONLY
  batch-job:
    enabled: true
    batch-size: 500
    cron: "0 * * * * ?"

logging:
  level:
    root: INFO
